import { Container } from "@nextui-org/react";
import Head from "next/head";

const Posts = () => {
  return (
    <>
      <Head>
        <title>Box Dev - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container></Container>
    </>
  );
};

export async function getStaticProps() {
  return {
    props: {},
  };
}

export default Posts;
