import { Box } from "@/components/box";
import Navbar from "@/components/navbar";
import Head from "next/head";
import SocialMedia from "@/components/socialMedia/socialMedia";
import { Main } from "@/components/main";
import Footer from "@/components/footer";

import { aboutMeText, goalsText, hobbiesText } from "../../lib/data/strings";
import SitesProps from "../../lib/models/sitesProps";
import { getSites } from "../../lib/getSites";
import metrics from "../../lib/data/metrics";

type Props = {
  sites: SitesProps;
};

const AboutMe = ({ sites }: Props) => {
  return (
    <>
      <Head>
        <title>About Me - Box Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar {...sites} />
      <div className="container mx-auto px-4">
        <Main>
          <h2 className="text-2xl font-bold m-0">About Me</h2>
          <hr className="my-2 border-gray-300" />
          <p>{aboutMeText}</p>
          <Box className="mt-6">
            <h3 className="text-xl font-semibold">Hobbies</h3>
            <p>{hobbiesText}</p>
          </Box>
          <Box className="mt-6">
            <h3 className="text-xl font-semibold">Goals</h3>
            <p>{goalsText}</p>
          </Box>
          <Box className="mt-5">
            <SocialMedia
              socialMedia={sites.socialMedia.filter((social) =>
                ["twitter", "instagram"].includes(social.code)
              )}
            />
          </Box>
        </Main>
      </div>
      <Footer {...sites} />
    </>
  );
};

export async function getStaticProps() {
  const sites = getSites();
  return {
    props: {
      sites,
      metrics,
    },
  };
}

export default AboutMe;
