import { Box } from "@/components/box";
import Navbar from "@/components/navbar";
import { Container, Divider, Text } from "@nextui-org/react";
import Head from "next/head";
import SocialMedia from "@/components/socialMedia/socialMedia";
import { Main } from "@/components/main";
import Footer from "@/components/footer";

import { aboutMeText, goalsText, hobbiesText } from "../../lib/data/strings";
import SitesProps from "../../lib/models/sitesProps";
import { getSites } from "../../lib/getSites";
import metrics from "../../lib/data/metrics";

type Props = {
  sites: SitesProps;
};

const AboutMe = ({ sites }: Props) => {
  return (
    <>
      <Head>
        <title>About Me - Box Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar {...sites} />
      <Container>
        <Main>
          <Text h2 css={{ margin: 0 }}>
            About Me
          </Text>
          <Divider css={{ marginBottom: 10 }} />
          <Text>{aboutMeText}</Text>
          <Box css={{ marginTop: 25 }}>
            <Text h3>Hobbies</Text>
            <Text>{hobbiesText}</Text>
          </Box>
          <Box css={{ marginTop: 25 }}>
            <Text h3>Goals</Text>
            <Text>{goalsText}</Text>
          </Box>
          <Box css={{ marginTop: 20 }}>
            <SocialMedia
              socialMedia={sites.socialMedia.filter((social) =>
                ["twitter", "instagram"].includes(social.code)
              )}
            />
          </Box>
        </Main>
      </Container>
      <Footer {...sites} />
    </>
  );
};

export async function getStaticProps() {
  const sites = getSites();
  return {
    props: {
      sites,
      metrics,
    },
  };
}

export default AboutMe;
