"use client";

import Head from "next/head";
import { Container } from "@nextui-org/react";
import Navbar from "@/components/navbar";
import { useRouter } from "next/router";
import { Main } from "@/components/main";

export default function Home() {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar />
      <Container>
        <Main></Main>
      </Container>
    </>
  );
}
