import { Box } from "@/components/box";
import Navbar from "@/components/navbar";
import Head from "next/head";
import SocialMedia from "@/components/socialMedia/socialMedia";
import { Main } from "@/components/main";

import socialMedia from "../../lib/data/socialMedia";
import {
  contactInstagram,
  contactLinkedIn,
  contactTwitter,
} from "../../lib/data/strings";
import Footer from "@/components/footer";
import Link from "next/link";
import { getSites } from "../../lib/getSites";
import SitesProps from "../../lib/models/sitesProps";

type Props = {
  sites: SitesProps;
};

const AboutMe = ({ sites }: Props) => {
  return (
    <>
      <Head>
        <title>Contact - Box Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar {...sites} />
      <Main>
        <h2 className="text-2xl font-bold mb-4">Contact</h2>
        <hr className="border-gray-300 mb-4" />
        <p className="mb-4">
          Thank you for your interest in my services! If you have any questions
          or would like to discuss your project requirements, please don&apos;t
          hesitate to contact me at{" "}
          <Link href="mailto: brandong.manzog@gmail.com">
            <span className="font-bold">brandong.manzog@gmail.com</span>
          </Link>
          . You can also connect with me on social media to stay up-to-date on
          my latest projects and industry insights.
        </p>
        <p className="mb-4">
          {contactLinkedIn}
          <Link
            href={
              socialMedia.find((social) => social.code === "linkedin")?.url!
            }
            target="_blank"
            className="font-bold"
          >
            Brandon Manzo
          </Link>
        </p>
        <p className="mb-4">
          {contactTwitter}
          <Link
            href={
              socialMedia.find((social) => social.code === "twitter")?.url!
            }
            target="_blank"
            className="font-bold"
          >
            @BoxBMG
          </Link>
        </p>
        <p className="mb-4">
          {contactInstagram}
          <Link
            href={
              socialMedia.find((social) => social.code === "instagram")?.url!
            }
            target="_blank"
            className="font-bold"
          >
            @bgManzo
          </Link>
        </p>
        <Box className="mt-5">
          <SocialMedia
            socialMedia={sites.socialMedia.filter((social) =>
              ["twitter", "instagram", "linkedin"].includes(social.code)
            )}
          />
        </Box>
      </Main>
      <Footer {...sites} />
    </>
  );
};

export async function getStaticProps() {
  const sites = getSites();
  return {
    props: {
      sites,
    },
  };
}

export default AboutMe;
