import Head from "next/head";
import { Container } from "@nextui-org/react";
import Navbar from "@/components/navbar";
import Presentation from "@/components/presentation";
import AboutMe from "@/components/aboutMe";
import Skills from "@/components/skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Box Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      <Container>
        <Presentation />
        <AboutMe />
        <Skills />
      </Container>
    </>
  );
}
