import { Box } from "@/components/box";
import Navbar from "@/components/navbar";
import RepositoriesTable from "@/components/projects/repositoriesTable";
import { Container, Divider, Text } from "@nextui-org/react";
import Head from "next/head";
import { projectsText } from "../../../lib/data/strings";
import socialMedia from "../../../lib/data/socialMedia";
import { Main } from "@/components/main";
import SocialMedia from "@/components/socialMedia/socialMedia";
import Footer from "@/components/footer";
import { getNavbarSites } from "../../../lib/getNavbarSites";
import NavbarProps from "../../../lib/models/navbarProps";

type Props = {
  navbarSites: NavbarProps;
};

const Projects = ({ navbarSites }: Props) => {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar {...navbarSites} />
      <Container>
        <Main>
          <Text h2 css={{ margin: 0 }}>
            Projects
          </Text>
          <Divider css={{ marginBottom: 10 }} />
          <Text>{projectsText}</Text>
          <Box css={{ marginTop: 20 }}>
            <SocialMedia
              socialMedia={socialMedia.filter((social) =>
                ["github", "blog"].includes(social.code)
              )}
            />
          </Box>
          <Box css={{ marginTop: 20 }}>
            <Text h3>Repositories</Text>
            <RepositoriesTable />
          </Box>
        </Main>
      </Container>
      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const navbarSites = getNavbarSites();
  return {
    props: {
      navbarSites,
    },
  };
}

export default Projects;
