import { Box } from "@/components/box";
import Navbar from "@/components/navbar";
import { Container, Divider, Text } from "@nextui-org/react";
import Head from "next/head";
import SocialMediaButton from "@/components/buttons/socialMediaButton";
import SkillsData from "@/components/skills";
import { Main } from "@/components/main";
import Metrics from "@/components/aboutMe/metrics";
import socialMedia from "../../../lib/data/socialMedia";
import { skillText } from "../../../lib/data/strings";
import metrics from "../../../lib/data/metrics";
import Footer from "@/components/footer";
import NavbarProps from "../../../lib/models/navbarProps";
import { getNavbarSites } from "../../../lib/getNavbarSites";

type Props = {
  navbarSites: NavbarProps;
};

const Skills = ({ navbarSites }: Props) => {
  return (
    <>
      <Head>
        <title>Skills</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar {...navbarSites} />
      <Container>
        <Main>
          <Text h2 css={{ margin: 0 }}>
            Skills
          </Text>
          <Divider css={{ marginBottom: 10 }} />
          <Text>{skillText}</Text>
          <Box css={{ marginTop: 20 }}>
            <SocialMediaButton
              socialMedia={
                socialMedia.find((social) => social.code === "linkedin")!
              }
            />
          </Box>
          <Box css={{ marginTop: 20 }}>
            <Metrics metrics={metrics} />
          </Box>
          <Box css={{ marginTop: 20 }}>
            <SkillsData />
          </Box>
        </Main>
      </Container>
      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const navbarSites = getNavbarSites();
  return {
    props: {
      navbarSites,
    },
  };
}

export default Skills;
